services:
  database:
    image: postgres:17
    container_name: pork_db
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pork_pgadmin
    env_file:
      - .env
    depends_on:
      - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pork_api
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    depends_on:
      - database
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pork_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - pgadmin
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pork_frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data: